variables:
  UV_VERSION: 0.5
  PYTHON_VERSION: 3.11
  BASE_LAYER: bookworm-slim
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy

default:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER

stages:
  - format
  - lint
  - test
  - doc

format:
  stage: format
  script:
    - uv run ruff format --check

lint:
  stage: lint
  script:
    - uv run ruff check

test:
  stage: test
  script:
    - uv run pytest

doc:
  stage: doc
  script:
    - uv run pdoc --html -o docs/ src/stem_volumes
