# """This module contains a mapping of tree genera to their respective stem volume formula function names."""

# # Auto-generated mapping of genus to formula function names
# genus_to_formulas = {
#     'Abies': [
#         'stem_volume_formula_1',
#         'stem_volume_formula_178',
#         'stem_volume_formula_2',
#         'stem_volume_formula_3',
#         'stem_volume_formula_4',
#         'stem_volume_formula_5',
#         'stem_volume_formula_6',
#         'stem_volume_formula_7',
#     ],
#     'Acacia': ['stem_volume_formula_8'],
#     'Acer': [
#         'stem_volume_formula_10',
#         'stem_volume_formula_11',
#         'stem_volume_formula_12',
#         'stem_volume_formula_9',
#     ],
#     'Alnus': [
#         'stem_volume_formula_13',
#         'stem_volume_formula_14',
#         'stem_volume_formula_15',
#         'stem_volume_formula_16',
#         'stem_volume_formula_17',
#         'stem_volume_formula_18',
#         'stem_volume_formula_19',
#         'stem_volume_formula_20',
#         'stem_volume_formula_21',
#         'stem_volume_formula_22',
#     ],
#     'Arbutus': ['stem_volume_formula_23'],
#     'Betula': [
#         'stem_volume_formula_24',
#         'stem_volume_formula_25',
#         'stem_volume_formula_26',
#         'stem_volume_formula_27',
#         'stem_volume_formula_28',
#         'stem_volume_formula_29',
#         'stem_volume_formula_30',
#         'stem_volume_formula_31',
#         'stem_volume_formula_32',
#         'stem_volume_formula_33',
#         'stem_volume_formula_34',
#         'stem_volume_formula_35',
#         'stem_volume_formula_36',
#         'stem_volume_formula_37',
#         'stem_volume_formula_38',
#         'stem_volume_formula_39',
#         'stem_volume_formula_54',
#     ],
#     'Carpinus': [
#         'stem_volume_formula_40',
#         'stem_volume_formula_41',
#         'stem_volume_formula_42',
#     ],
#     'Chamaecyparis': ['stem_volume_formula_43'],
#     'Corylus': ['stem_volume_formula_44', 'stem_volume_formula_45'],
#     'Fagus': [
#         'stem_volume_formula_46',
#         'stem_volume_formula_47',
#         'stem_volume_formula_48',
#         'stem_volume_formula_49',
#         'stem_volume_formula_50',
#         'stem_volume_formula_51',
#         'stem_volume_formula_52',
#         'stem_volume_formula_53',
#     ],
#     'Fraxinus': [
#         'stem_volume_formula_55',
#         'stem_volume_formula_56',
#         'stem_volume_formula_57',
#         'stem_volume_formula_58',
#         'stem_volume_formula_59',
#         'stem_volume_formula_60',
#         'stem_volume_formula_61',
#         'stem_volume_formula_62',
#         'stem_volume_formula_63',
#     ],
#     'Larix': [
#         'stem_volume_formula_64',
#         'stem_volume_formula_65',
#         'stem_volume_formula_66',
#         'stem_volume_formula_67',
#         'stem_volume_formula_68',
#         'stem_volume_formula_69',
#         'stem_volume_formula_70',
#         'stem_volume_formula_71',
#         'stem_volume_formula_72',
#         'stem_volume_formula_73',
#         'stem_volume_formula_74',
#         'stem_volume_formula_75',
#         'stem_volume_formula_76',
#         'stem_volume_formula_77',
#         'stem_volume_formula_78',
#         'stem_volume_formula_79',
#         'stem_volume_formula_80',
#         'stem_volume_formula_81',
#     ],
#     'Picea': [
#         'stem_volume_formula_100',
#         'stem_volume_formula_101',
#         'stem_volume_formula_102',
#         'stem_volume_formula_103',
#         'stem_volume_formula_104',
#         'stem_volume_formula_105',
#         'stem_volume_formula_106',
#         'stem_volume_formula_107',
#         'stem_volume_formula_108',
#         'stem_volume_formula_109',
#         'stem_volume_formula_110',
#         'stem_volume_formula_111',
#         'stem_volume_formula_112',
#         'stem_volume_formula_113',
#         'stem_volume_formula_114',
#         'stem_volume_formula_115',
#         'stem_volume_formula_116',
#         'stem_volume_formula_117',
#         'stem_volume_formula_118',
#         'stem_volume_formula_119',
#         'stem_volume_formula_120',
#         'stem_volume_formula_121',
#         'stem_volume_formula_122',
#         'stem_volume_formula_123',
#         'stem_volume_formula_124',
#         'stem_volume_formula_125',
#         'stem_volume_formula_126',
#         'stem_volume_formula_127',
#         'stem_volume_formula_128',
#         'stem_volume_formula_129',
#         'stem_volume_formula_130',
#         'stem_volume_formula_82',
#         'stem_volume_formula_83',
#         'stem_volume_formula_84',
#         'stem_volume_formula_85',
#         'stem_volume_formula_86',
#         'stem_volume_formula_87',
#         'stem_volume_formula_88',
#         'stem_volume_formula_89',
#         'stem_volume_formula_90',
#         'stem_volume_formula_91',
#         'stem_volume_formula_92',
#         'stem_volume_formula_93',
#         'stem_volume_formula_94',
#         'stem_volume_formula_95',
#         'stem_volume_formula_96',
#         'stem_volume_formula_97',
#         'stem_volume_formula_98',
#         'stem_volume_formula_99',
#     ],
#     'Pinus': [
#         'stem_volume_formula_131',
#         'stem_volume_formula_132',
#         'stem_volume_formula_133',
#         'stem_volume_formula_134',
#         'stem_volume_formula_135',
#         'stem_volume_formula_136',
#         'stem_volume_formula_137',
#         'stem_volume_formula_138',
#         'stem_volume_formula_139',
#         'stem_volume_formula_140',
#         'stem_volume_formula_141',
#         'stem_volume_formula_142',
#         'stem_volume_formula_143',
#         'stem_volume_formula_144',
#         'stem_volume_formula_145',
#         'stem_volume_formula_146',
#         'stem_volume_formula_147',
#         'stem_volume_formula_148',
#         'stem_volume_formula_149',
#         'stem_volume_formula_150',
#         'stem_volume_formula_151',
#         'stem_volume_formula_152',
#         'stem_volume_formula_153',
#         'stem_volume_formula_154',
#         'stem_volume_formula_155',
#         'stem_volume_formula_156',
#         'stem_volume_formula_157',
#         'stem_volume_formula_158',
#         'stem_volume_formula_159',
#         'stem_volume_formula_160',
#         'stem_volume_formula_161',
#         'stem_volume_formula_162',
#         'stem_volume_formula_163',
#         'stem_volume_formula_164',
#         'stem_volume_formula_165',
#         'stem_volume_formula_166',
#         'stem_volume_formula_167',
#         'stem_volume_formula_168',
#         'stem_volume_formula_169',
#         'stem_volume_formula_170',
#         'stem_volume_formula_171',
#         'stem_volume_formula_172',
#         'stem_volume_formula_173',
#         'stem_volume_formula_174',
#         'stem_volume_formula_175',
#         'stem_volume_formula_176',
#         'stem_volume_formula_177',
#     ],
#     'Populus': [
#         'stem_volume_formula_179',
#         'stem_volume_formula_180',
#         'stem_volume_formula_181',
#         'stem_volume_formula_182',
#         'stem_volume_formula_183',
#         'stem_volume_formula_184',
#         'stem_volume_formula_185',
#         'stem_volume_formula_186',
#         'stem_volume_formula_187',
#         'stem_volume_formula_188',
#         'stem_volume_formula_189',
#         'stem_volume_formula_190',
#         'stem_volume_formula_191',
#     ],
#     'Prunus': ['stem_volume_formula_192'],
#     'Pseudotsuga': [
#         'stem_volume_formula_193',
#         'stem_volume_formula_194',
#         'stem_volume_formula_195',
#         'stem_volume_formula_196',
#         'stem_volume_formula_197',
#         'stem_volume_formula_198',
#         'stem_volume_formula_199',
#     ],
#     'Quercus': [
#         'stem_volume_formula_200',
#         'stem_volume_formula_201',
#         'stem_volume_formula_202',
#         'stem_volume_formula_203',
#         'stem_volume_formula_204',
#         'stem_volume_formula_205',
#         'stem_volume_formula_206',
#         'stem_volume_formula_207',
#         'stem_volume_formula_208',
#         'stem_volume_formula_209',
#         'stem_volume_formula_210',
#         'stem_volume_formula_211',
#         'stem_volume_formula_212',
#         'stem_volume_formula_213',
#         'stem_volume_formula_214',
#         'stem_volume_formula_215',
#         'stem_volume_formula_216',
#         'stem_volume_formula_217',
#     ],
#     'Salix': [
#         'stem_volume_formula_218',
#         'stem_volume_formula_219',
#         'stem_volume_formula_220',
#         'stem_volume_formula_221',
#     ],
#     'Sorbus': ['stem_volume_formula_222'],
#     'Thuja': ['stem_volume_formula_223', 'stem_volume_formula_224'],
#     'Tilia': ['stem_volume_formula_225'],
#     'Tsuga': ['stem_volume_formula_226', 'stem_volume_formula_227'],
#     'Ulmus': [
#         'stem_volume_formula_228',
#         'stem_volume_formula_229',
#         'stem_volume_formula_230',
#     ],
# }
