name: Run_tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UV_VERSION: 0.5
  PYTHON_VERSION: "3.11"
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:${{ env.UV_VERSION }}-python${{ env.PYTHON_VERSION }}-${{ env.BASE_LAYER }}
    steps:
      - uses: actions/checkout@v3
      - run: uv run ruff format --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:${{ env.UV_VERSION }}-python${{ env.PYTHON_VERSION }}-${{ env.BASE_LAYER }}
    steps:
      - uses: actions/checkout@v3
      - run: uv run ruff check

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:${{ env.UV_VERSION }}-python${{ env.PYTHON_VERSION }}-${{ env.BASE_LAYER }}
    steps:
      - uses: actions/checkout@v3
      - run: uv run pytest

  doc:
    name: Build Docs
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:${{ env.UV_VERSION }}-python${{ env.PYTHON_VERSION }}-${{ env.BASE_LAYER }}
    steps:
      - uses: actions/checkout@v3
      - run: uv run pdoc --html -o docs/ src/stem_volumes
      - name: Upload Docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/
