name: Run CI Workflows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UV_VERSION: 0.5
  PYTHON_VERSION: "3.11"
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install uv
        run: pip install uv
      - name: Install project deps
        run: uv pip install --system
      - name: Run ruff format check
        run: uv run ruff format --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install uv
        run: pip install uv
      - name: Install project deps
        run: uv pip install --system
      - name: Run ruff check
        run: uv run ruff check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install uv
        run: pip install uv
      - name: Install project deps
        run: uv pip install --system
      - name: Run tests
        run: uv run pytest --strict-markers

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install uv
        run: pip install uv
      - name: Install project deps
        run: uv pip install --system
      - name: Generate documentation with pdoc
        run: uv run pdoc --html -o docs/ src/stem_volumes
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/
