name: Run CI Workflows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:0.5-python3.11-bookworm-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          uv pip install --system .
          uv pip install --system --editable .[dev]


      - name: Run formatter check
        run: uv run ruff format --check
        continue-on-error: true

      - name: Format code with Ruff
        run: uv run ruff format

      - name: Run linter
        run: uv run ruff check

      - name: Run tests
        run: uv run pytest

      - name: Build documentation
        run: uv run pdoc --html -o docs/ src/stem_volumes

